name: Github Actions 
on: [push]
jobs:
  Linter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Dependencies 
        run: npm install
      
      - name: Init Linter
        run: npm run lint
  Cypress_job:
    runs-on: ubuntu-latest
    needs: Linter_job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Run Cypress Job
        id: my-cypress-test
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          config-file: cypress.json
          build: npm run build
          start: npm start
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACTIONS_TOKEN }}

      - name: Save Test Results
        run: echo ${{ steps.my-cypress-test.outcome }} > result.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: result.txt
          path: result.txt
  Add_badge_job:
    runs-on: ubuntu-latest
    if: always()
    needs: Cypress_job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Download Changes Of Artifact
        uses: actions/download-artifact@v2
        with:
          name: result.txt
      
      - name: Create Output Based In The Artifact
        id: my-cypress-test
        run: echo "::set-output name=cypress_outcome::$(cat result.txt)"
      
      - name: Create Badge Of Result
        uses: ./.github/actions/badge/
        id: readme
        with:
          my-cypress-test: ${{ steps.my-cypress-test.outputs.cypress_outcome }}
      
      - name: Upload The Changes In The Readme
        run: | 
            git config user.email "adri7agu@gmail.com"
            git config user.name "AdriRameti"
            git pull
            git add .
            git commit --allow-empty -m "Readme" 
            git remote set-url origin https://AdriRameti:${{ secrets.GH_ACTIONS_TOKEN }}@github.com/AdriRameti/Practica_Github_Actions.git
            git push
  Deploy_job:
    runs-on: ubuntu-latest
    needs: Cypress_job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Our App On Vercel Plataform
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GH_ACTIONS_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: ./